### ISSUE TITLE
Migrate away from Uglify

### ISSUE THREAD

**Issue by ChristianMurphy** [elmsln/wcfactory#27]
Uglify-js does not have support for ES6, and the existing ES6 support (Uglify-es) has been deprecated.
https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058
To support minification in modern browser build targets, we may need to migrate to an alternative library.

Some alternatives include https://github.com/terser-js/terser and https://github.com/babel/minify

**Comment by btopro** [comment]
hmm, thought I was using terser already but def worth doing if not.

**Comment by ChristianMurphy** [comment]
https://github.com/elmsln/wcfactory/blob/eb50c2d8ff8a699c665ab4727e58a45de28e7b19/packages/generator-wcfactory/generators/init/templates/scripts/rollup.config.factory.js#L4

**Comment by btopro** [comment]
oh, well that would explain why my roll ups are failing since it's attempting to roll up es6 :)

This is something I had previously fixed and then borked in juggling all these dev branches I had.

So which should we use, terser which has a rollup plugin or the babel minify one (which probably does too, haven't looked)
