### ISSUE TITLE
_.gitignore conflict causing CI to fail

### ISSUE THREAD

**Issue by ChristianMurphy** [elmsln/wcfactory#385]
`_.gitignore` is running into a conflict that needs to be manually overwritten.
This is causing CI to timeout waiting for command line feedback on how to resolve the conflict.

```
 conflict packages/generator-wcfactory/generators/start/templates/_.gitignore
? Overwrite packages/generator-wcfactory/generators/start/templates/_.gitignore?
 (ynaxdH) 
```

https://travis-ci.com/elmsln/wcfactory/jobs/174210814#L555

_Originally posted by @ChristianMurphy in https://github.com/elmsln/wcfactory/pull/381#issuecomment-459785731_

**Comment by btopro** [comment]
blarg

**Comment by ThatJoeMoore** [comment]
Hmm. I thought I had resolved that before pushing my PR. I'll dig into it tomorrow.

**Comment by ThatJoeMoore** [comment]
It appears that this is because the Travis tests are running in the same directory as the source, which leaves the heuristic I wrote to do the _.gitignore -> .gitignore conversion unable to distinguish between the templatePath() and the destinationPath(). I can add an extra check to exclude everything in templatePath(), but it might be a better long-term solution to make the wcf test commands run in a different directory, as I can see running it in the same directory causing other problems in the future.

**Comment by ThatJoeMoore** [comment]
Yup - I just confirmed that changing the heuristic fixes this immediate issue, but it ends up conflicting on the .gitignore in the root of the repo.  The solution will be to run the travis wcf commands in a different dir.  Unfortunately, I'm not familiar enough with Travis to do so.  I'll still push a commit that changes the heuristic to always exclude templatePath.
